name: Terminal

options:
  bundleIdPrefix: com.Terminal.app

targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: Term.swift
      - path: tools

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Terminal.app
      IPHONEOS_DEPLOYMENT_TARGET: 15.0

    info:
      path: MyApp/Info.plist
